version: '1.0'
name: pipeline-c
displayName: pipeline-c
triggers:
  trigger: auto
  push:
    branches:
      prefix:
        - master
  schedule:
    - cron: '* 11 2 * * ? *'
stages:
  - name: stage-8d77b12f
    displayName: c
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: build@python
        name: build_python
        displayName: Python 构建
        pythonVersion: '3.9'
        commands:
          - pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple
          - '# 可以使用pip下载依赖'
          - pip install --user -r requirements.txt
          - python --version
          - python c.py
        artifacts:
          - name: BUILD_ARTIFACT
            path:
              - ./
        caches: []
        notify: []
        strategy:
          retry: '0'
