name: cccc
on:
  schedule:
    - cron: "34 0/7 * * 1,2,3,4,5"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
          pip install beautifulsoup4
      - name: cccc
        run: |
          python cccc.py
