name: CT
on:
  schedule:
    - cron: "3 2/7 * * *"
    - workflow_dispatch
    - push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
          pip install beautifulsoup4
      - name: cccc
        run: |
          python cT.py
